import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

// hooks
import { useState } from "react";

// images
import profileImg from "../public/images/profile.png";
import DesignImg from "../public/images/design.png";
import PortfolioImg from "../public/images/web1.png";

// icons
import { BsGithub, BsLinkedin, BsTwitter } from "react-icons/bs";

import { CgDarkMode } from "react-icons/cg";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  // function 
  const [darkmode, setdarkmode] = useState (false);

  return (
    <div className={darkmode ? "dark" : ""}>
      <Head>
        <title>ChanukaDasanayaka.io</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-yellow-50 min-h-screen text-black px-10 md:px-20 lg:px-30 dark:bg-black">
        {/* Nav */}
        <nav className=" py-10 flex justify-between">
          <h1 className=" font-bold md:text-xl dark:text-white">Portfolio Title</h1>
          <ul className=" flex items-center">
            <li>
              <CgDarkMode onClick={()=> setdarkmode(!darkmode)} className=" mx-5 text-3xl cursor-pointer dark:text-white" />
            </li>
            <li>
              {" "}
              <a
                href=""
                className=" bg-yellow-400 px-4 py-2 border-none rounded-md"
              >
                Resume
              </a>
            </li>
          </ul>
        </nav>
        {/* Nav End */}
        {/* Profile image */}
        <div className=" m-auto relative bg-gradient-to-b from-yellow-200 w-80 h-8- p-5 rounded-full ">
          <Image src={profileImg} alt="profile-image" />
        </div>
        {/* Name and Description */}
        <div className="text-center p-5">
          <h1 className=" font-bold text-purple-700 text-5xl">
            Chanuka Dasanayaka
          </h1>
          <h3 className="py-4 text-2xl dark:text-white">
            Undergraduate at University of Colombo{" "}
          </h3>
          {/* Social Icons */}
          <div className="text-5xl flex gap-16 text-gray-600 justify-center my-6 ">
            <a href="https://github.com/">
              <BsGithub className="hover:bg-blue-300" />
            </a>
            <a href="https://www.linkedin.com/">
              <BsLinkedin className="hover:bg-blue-300"  />
            </a>
            <a href="https://twitter.com/">
              <BsTwitter className="hover:bg-blue-300"  />
            </a>
          </div>
          <p className=" py-2 text-gray-400 leading-6 mx-auto text-sm md:text-md dark:text-white">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio
            voluptate adipisci enim, necessitatibus error numquam facere
            deserunt qui doloremque odio nulla blanditiis obcaecati. Omnis unde
            possimus cum nostrum accusantium minima.
          </p>
        </div>

        {/* Services */}
        <section>
          <h3 className="font-bold opacity-60 text-3xl py-2 dark:text-white dark:opacity-95">
            Services | Offer
          </h3>
          <p className=" py-2 text-gray-400 leading-6 mx-auto text-sm ">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio
            voluptate adipisci enim, necessitatibus error numquam facere
            deserunt qui doloremque odio nulla blanditiis obcaecati. Omnis unde
            possimus cum nostrum accusantium minima.
          </p>
          <div className=" md:flex lg:flex gap-10 mx-auto">
            {/*card1 */}
            <div className="text-center bg-yellow-300 shadow-sm p-5 rounded-xl my-5">
              <Image
                src={DesignImg}
                alt="card1"
                width={100}
                height={100}
                className="inline"
              />
              <h2 className=" text-2xl font-bold opacity-60">
                Front End Development
              </h2>
              <p className=" leading-6 py-2 text-gray-800 text-sm">
                adipisicing elit. Quam sequi tempora at nemo, esse suscipit quod
                adipisci labore accusamus similique!
              </p>
            </div>
            {/*card2 */}
            <div className="text-center bg-yellow-300 shadow-sm p-5 rounded-xl my-5">
              <Image
                src={DesignImg}
                alt="card1"
                width={100}
                height={100}
                className="inline"
              />
              <h2 className=" text-2xl font-bold opacity-60">Graphic Design</h2>
              <p className=" leading-6 py-2 text-gray-800 text-sm">
                adipisicing elit. Quam sequi tempora at nemo, esse suscipit quod
                adipisci labore accusamus similique!
              </p>
            </div>
            {/*card3 */}
            <div className="text-center bg-yellow-300 shadow-sm p-5 rounded-xl my-5">
              <Image
                src={DesignImg}
                alt="card1"
                width={100}
                height={100}
                className="inline"
              />
              <h2 className=" text-2xl font-bold opacity-60">IT Help Desk</h2>
              <p className=" leading-6 py-2 text-gray-800 text-sm">
                adipisicing elit. Quam sequi tempora at nemo, esse suscipit quod
                adipisci labore accusamus similique!
              </p>
            </div>
          </div>
        </section>
        {/* end services section */}
        {/* portfolio section */}
        <section>
          <div className="pb-4">
            <h2 className=" text-3xl py-5 font-bold opacity-50 dark:text-white dark:opacity-100">Portfolio</h2>
            <p className=" text-sm py-2 text-gray-400 leading-6">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Temporibus soluta sit, ducimus eius rerum culpa perferendis
              blanditiis provident quidem deserunt reprehenderit. Soluta nemo
              necessitatibus nihil, adipisci ab{" "}
            </p>
            <div className="flex flex-col gap-10 p-2 lg:flex lg:flex-row lg:flex-wrap">
              <div className=" basis-1/3 flex-1">
                <Image
                  src={PortfolioImg}
                  alt={"portfolio one"}
                  layout="responsive"
                  className=" rounded-lg object-cover"
                />
              </div>

              <div className=" basis-1/3 flex-1">
                <Image
                  src={PortfolioImg}
                  alt={"portfolio one"}
                  layout="responsive"
                  className=" rounded-lg object-cover"
                />
              </div>

              <div className=" basis-1/3 flex-1">
                <Image
                  src={PortfolioImg}
                  alt={"portfolio one"}
                  layout="responsive"
                  className=" rounded-lg object-cover"
                />
              </div>

              <div className=" basis-1/3 flex-1">
                <Image
                  src={PortfolioImg}
                  alt={"portfolio one"}
                  layout="responsive"
                  className=" rounded-lg object-cover"
                />
              </div>

              <div className=" basis-1/3 flex-1">
                <Image
                  src={PortfolioImg}
                  alt={"portfolio one"}
                  layout="responsive"
                  className=" rounded-lg object-cover"
                />
              </div>

              <div className=" basis-1/3 flex-1">
                <Image
                  src={PortfolioImg}
                  alt={"portfolio one"}
                  layout="responsive"
                  className=" rounded-lg object-cover"
                />
              </div>
            </div>
          </div>
        </section>
        {/* end portfolio section */}
        {/* footer */}
        <section>
          <footer className=" border-t-2 border-black dark:border-white text-sm opacity-70 flex flex-col gap-5  justify-center py-8 lg:flex-row lg:items-center">
            <div>
              <h3 className=" text-base font-bold pb-2 dark:text-white">
                Contact me more details
              </h3>
              <p className="opacity-40 dark:text-white dark:opacity-100">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo
                eius repudiandae ad vero praesentium cumque, laboriosam
                voluptatum dolorum, blanditiis consequuntur sed ratione iure at
                quidem aperiam a iste sequi deleniti?
              </p>
            </div>
            <div className="text-5xl flex gap-16 text-gray-600 justify-center">
              <a href="https://github.com/">
                <BsGithub />
              </a>
              <a href="https://www.linkedin.com/">
                <BsLinkedin />
              </a>
              <a href="https://twitter.com/">
                <BsTwitter />
              </a>
            </div>
          </footer>
        </section>
        {/* end footer */}
      </main>
    </div>
  );
}
